# Rust 代码格式化配置
edition = "2021"
max_width = 100
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
# 以下是 nightly 特性，在 stable 中不可用
# format_code_in_doc_comments = true
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"