name: CI with sccache

on:
  workflow_dispatch:
  push:
    branches: [ test-sccache ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  SQLX_OFFLINE: true
  DATABASE_URL: sqlite:data.db
  CI: true
  # sccache配置
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_CACHE_SIZE: "2G"

jobs:
  test-sccache:
    name: Test sccache
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    
    # 使用Mozilla官方的sccache-action
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.7
    
    - name: Check sccache
      run: |
        # 验证sccache安装
        which sccache
        sccache --version
        
        # 显示初始统计
        sccache --show-stats
    
    - name: Build with sccache
      run: |
        # 第一次构建（缓存未命中）
        echo "=== First build (cache miss) ==="
        time cargo build --release
        
        # 显示缓存统计
        echo "=== Cache stats after first build ==="
        sccache --show-stats
        
        # 清理target目录
        cargo clean
        
        # 第二次构建（缓存命中）
        echo "=== Second build (cache hit) ==="
        time cargo build --release
        
        # 最终统计
        echo "=== Final cache stats ==="
        sccache --show-stats